import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  SidebarProvider,
  SidebarTrigger,
} from "@/ui/shadcn/components/sidebar";
import SideMenu from "@/ui/components/sideMenu/sideMenu";
import ModalCreateInimigo from "@/ui/components/modals/inimigos/modalCreateInimigo";
import ModalListInimigo from "@/ui/components/modals/inimigos/modalListInimigo";
import ModalSelectInimigo from "@/ui/components/modals/inimigos/modalSelectInimigo";
import ModalCreatePersonagem from "@/ui/components/modals/personagem/modalCreatePersonagem";
import ModalListPersonagem from "@/ui/components/modals/personagem/modalLisPersonagem";
import ModalSelectPersonagem from "@/ui/components/modals/personagem/modalSelectPersonagem";
import ModalCombatInimigos from "@/ui/components/modals/inimigos/modalCombatInimigos";
import ModalCombatPersonagem from "@/ui/components/modals/personagem/modalCombatPersonagem";
import ModalEditInimigo from "@/ui/components/modals/inimigos/modalEditInimigos";
import ModalEditPersonagem from "@/ui/components/modals/personagem/modalEditPersonagem";
import ModalEditPersonagemTabela from "@/ui/components/modals/personagem/modalEditPersonagemTabela";
import ModalEditCombat from "@/ui/components/modals/combate/modalEditCombat";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tabletop RPG Combat Assistant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        <SidebarProvider>
          <div className="flex min-h-screen w-full">
            {/* Sidebar */}
            <aside className="hidden md:block">
              <SideMenu />
            </aside>

            {/* Conteúdo principal */}
            <main className="flex-1 flex flex-col">
              {/* Trigger visível em telas pequenas */}
              <div className="md:hidden p-2">
                <SidebarTrigger />
              </div>

              {children}

              {/* Modais */}
              <div>
                <ModalCreateInimigo />
                <ModalListInimigo />
                <ModalEditInimigo />
                <ModalSelectInimigo />
                <ModalCombatInimigos />

                <ModalCreatePersonagem />
                <ModalListPersonagem />
                <ModalSelectPersonagem />
                <ModalCombatPersonagem />
                <ModalEditPersonagem />
                <ModalEditPersonagemTabela />

                <ModalEditCombat />
              </div>
            </main>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}