import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  SidebarProvider,
  SidebarTrigger,
} from "@/ui/shadcn/components/sidebar";
import SideMenu from "@/ui/components/sideMenu/sideMenu";
import ModalCreateInimigo from "@/ui/components/modals/inimigos/modalCreateInimigo";
import ModalListInimigo from "@/ui/components/modals/inimigos/modalListInimigo";
import ModalSelectInimigo from "@/ui/components/modals/inimigos/modalSelectInimigo";
import ModalCreatePersonagem from "@/ui/components/modals/personagem/modalCreatePersonagem";
import ModalListPersonagem from "@/ui/components/modals/personagem/modalLisPersonagem";
import ModalSelectPersonagem from "@/ui/components/modals/personagem/modalSelectPersonagem";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        <SidebarProvider>
          <div className="flex min-h-screen w-full">
            {/* Sidebar fixa */}
            <SideMenu />

            {/* Conteúdo principal da aplicação */}
            <main className="flex-1 flex flex-col">
              <SidebarTrigger />
              {children}
            </main>
          </div>

          {/* Modais (já estão fora da main, o que é correto) */}
          <ModalCreateInimigo />
          <ModalListInimigo />
          <ModalSelectInimigo />

          <ModalCreatePersonagem />
          <ModalListPersonagem />
          <ModalSelectPersonagem />
        </SidebarProvider>
      </body>
    </html>
  );
}